from pipeline_config import settings
import json


class GraphPipelineLogger:
    def __init__(self, enabled: bool = False):
        self.enabled = enabled

    # =====================================================
    # LEVEL 1: Raw ontologies generated by LLM
    # =====================================================

    def log_llm_batch(
        self,
        batch_id,
        document_name,
        extracted_list,
    ):
        if not self.enabled:
            return

        with open(
            settings.config["llm_generated_ontologies"],
            "a",
            encoding="utf-8",
        ) as f:
            self._write_batch_header(
                f,
                batch_id,
                document_name,
            )

            json.dump(
                [
                    item.model_dump()
                    for item in extracted_list
                ],
                f,
                ensure_ascii=False,
                indent=2,
            )

            f.write("\n")


    # =====================================================
    # LEVEL 2: Validation result
    # =====================================================

    def log_validation_batch(
        self,
        batch_id,
        document_name,
        validated,
        failures,
    ):
        if not self.enabled:
            return

        with open(
            settings.config["validated_ontologies"],
            "a",
            encoding="utf-8",
        ) as f:
            self._write_batch_header(
                f,
                batch_id,
                document_name,
            )

            f.write("VALIDATED ONTOLOGIES\n")
            f.write("-" * 100 + "\n")

            json.dump(
                [
                    item.model_dump()
                    for item in validated
                ],
                f,
                ensure_ascii=False,
                indent=2,
            )

            f.write("\n\nVALIDATION FAILURES\n")
            f.write("-" * 100 + "\n")

            json.dump(
                [
                    item.model_dump()
                    for item in failures
                ],
                f,
                ensure_ascii=False,
                indent=2,
            )

            f.write("\n")


    # =====================================================
    # LEVEL 3: Deduplicated entities / relationships
    # =====================================================

    def log_dedup_batch(
        self,
        batch_id,
        document_name,
        entities,
        relationships,
    ):
        if not self.enabled:
            return

        with open(
            settings.config["inner_batches_result"],
            "a",
            encoding="utf-8",
        ) as f:
            self._write_batch_header(
                f,
                batch_id,
                document_name,
            )

            f.write("ENTITIES\n")
            f.write("-" * 100 + "\n")

            json.dump(
                [
                    entity.model_dump()
                    for entity in entities
                ],
                f,
                ensure_ascii=False,
                indent=2,
            )

            f.write("\n\nRELATIONSHIPS\n")
            f.write("-" * 100 + "\n")

            json.dump(
                [
                    relationship.model_dump()
                    for relationship in relationships
                ],
                f,
                ensure_ascii=False,
                indent=2,
            )

            f.write("\n")


    # =====================================================
    # Shared formatting
    # =====================================================

    def _write_batch_header(
        self,
        file,
        batch_id,
        document_name,
    ):
        file.write("\n\n" + "=" * 100 + "\n")
        file.write(
            f"BATCH {batch_id} | DOCUMENT: {document_name}\n"
        )
        file.write("=" * 100 + "\n\n")